kind: Service
apiVersion: v1
metadata:
  name: telegram-bot
  labels:
    app: telegram-bot
spec:
  selector:
    app: telegram-bot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: NodePort
