version: '3.7'
services:
  passwordapi-1:
    image: "nicopaez/password-api"
  passwordapi-2:
    image: "nicopaez/password-api"
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - passwordapi-1
      - passwordapi-2